Added check for URL validity and root privledge

diff --git a/scripts/install_nagios_xi_nrpe_interactive b/scripts/install_nagios_xi_nrpe_interactive
--- a/scripts/install_nagios_xi_nrpe_interactive
+++ b/scripts/install_nagios_xi_nrpe_interactive
@@ -15,18 +15,31 @@
 # This script is tested under CentOS 6, but should
 # work indentically for RedHat/CentOS 7.
 
+if [ $UID -ne 0 ]; then
+    echo "Script must be run as root.  Try again!"
+    exit 1
+fi
+
+ASSET_URL="https://assets.nagios.com/downloads/nagiosxi/agents/linux-nrpe-agent.tar.gz"
 
 # Grab the nagios agent
-curl https://assets.nagios.com/downloads/nagiosxi/agents/linux-nrpe-agent.tar.gz | tar -xzvf - -C /tmp
+curl $ASSET_URL | tar -xzvf - -C /tmp
 
-# Install using the fullinstall
-cd /tmp/linux-nrpe-agent
-./fullinstall
+TMP_FILE=/tmp/linux-nrpe-agent
 
-error() {
+if [ -d "$TMP_FILE" ]; then
+    echo "Unable to download and untar Nagios XI agent"
+    echo "Bailing..."
+    exit 1
+fi
+
+# Install using the full install script
+cd "$TMP_FILE" && ./fullinstall
+
+nrpe_install_error() {
     echo "Installation exited prematurely."
     echo
-    echo "Check log files in /tmp/linux-nrpe-agent for more details"
+    echo "Check log files in $TMP_FILE for more details"
     exit 1
 }
 
@@ -35,9 +48,9 @@ NRPE_CFG=$(ls /usr/local/nagios/etc/nrpe.cfg)
 XINET_CFG=$(ls /etc/xinetd.d/nrpe)
 
 # Check status of cfg files
-[ -z "$XINETD_PID" ] && error
-[ -z "$NRPE_CFG" ] && error
-[ -z "$XINET_CFG" ] && error
+[ -z "$XINETD_PID" ] && nrpe_install_error
+[ -z "$NRPE_CFG" ] && nrpe_install_error
+[ -z "$XINET_CFG" ] && nrpe_install_error
 
 # List configuration locations
 echo "Process finishing..."
